name: Merge Language Files

on:
  pull_request:
    paths:
      - 'locate/**/*.yml'

jobs:
  merge-translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # 使用 Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Run translation processing script
      run: node processYamlFiles.js

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'locate/**/*.yml'
        message: 'Update language files after merging translations'
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'

    - name: Create Pull Request for merged translations
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Merged translations'
        body: 'This pull request includes updated translations after processing.'
        base: main
        branch: update-translations
